= lab-insurance-cloud-config-server

image:https://travis-ci.org/labcabrera/lab-insurance-cloud-config-server.svg?branch=master["Build Status", link="https://travis-ci.org/labcabrera/lab-insurance-cloud-config-server"]

== Introducción

Servidor de configuración de la aplicación https://github.com/labcabrera/lab-insurance[lab-insurance]
basado en https://cloud.spring.io/spring-cloud-config/[Spring Cloud Config].

El repositorio que contiene la configuración es:
https://github.com/labcabrera/lab-insurance-cloud-config[lab-insurance-cloud-config].

== Consultando la configuración

Una vez ejecutándose la aplicación podemos hacer una petición HTTP para consultar nuestra
configuración del siguiente modo:

----
curl http://localhost:8888/insurance-common/default/
----

Siendo _insurance-common_ el nombre de la configuración que deseamos consultar y _default_ el
profile.

Si la aplicación está funcionando correctamente debería consultar el repositorio de Github donde
está alojada nuestra configuración y devolver un JSON con la siguiente estructura:

[source,json]
----
{
  "name": "insurance-common",
  "profiles": [
    "default"
  ],
  "label": null,
  "version": "0134c35ce7da5b7253f50d1314810272b57fe8f6",
  "state": null,
  "propertySources": [
    {
      "name": "https://github.com/labcabrera/lab-insurance-cloud-config/insurance-common.yml",
      "source": {
        "configuration.projectName": "insurance-common",
        "spring.data.mongodb.uri": "mongodb://localhost:27017/lab-insurance",
        "eureka.registerWithEureka": true,
        "eureka.fetchRegistry": true,
        "eureka.client.serviceUrl.defaultZone": "http://lab-insurance-eureka.eu-west-1.elasticbeanstalk.com/eureka/",
        "management.security.enabled": false,
        "logging.level.org": "INFO"
      }
    }
  ]
}
----

== Docker

Las imágenes están disponibles en https://hub.docker.com/r/labcabrera/lab-insurance-cloud-config-server/.

Para crear la imagen docker se utiliza el plugin https://github.com/palantir/gradle-docker[palantir]
de gradle.

Para crear la imagen simplemente ejecutaremos:

----
$ gradle build docker
----

Y después simplemente tendremos que ejecutar nuestra imagen del modo habitual:

----
$ docker run -i -p 8888:8888 -t labcabrera/lab-insurance-cloud-config-server
---- 

A partir del plugin también podemos hacer el push a https://hub.docker.com/[Docker Hub]:

----
$ gradle dockerPush
----

== Instalando la aplicación en Heroku

Para ejecutar la aplicación bastará con hacer:

----
heroku create config-lab-insurance

git push heroku master
----

Y cuando termine el proceso será accesible desde:

https://config-lab-insurance.herokuapp.com/insurance-common/default

Más información sobre cómo instalar aplicaciones Spring Boot en Heroku en el siguiente link:

https://devcenter.heroku.com/articles/deploying-spring-boot-apps-to-heroku.

== Resources

* https://github.com/palantir/gradle-docker
* https://plugins.gradle.org/plugin/com.palantir.docker
* https://spring.io/guides/gs/spring-boot-docker/
